# Generated by Django 3.1.4 on 2021-01-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('last_change', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('schoolhour', models.PositiveIntegerField(blank=True, null=True)),
                ('schoolsubject', models.CharField(blank=True, max_length=15, null=True)),
                ('schoolroom', models.CharField(blank=True, max_length=15, null=True)),
                ('week', models.CharField(blank=True, choices=[('A', 'A Woche'), ('B', 'B WocheB Woche')], max_length=1, null=True)),
                ('dropped', models.BooleanField(default=False)),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vpapp.schoolclass')),
            ],
            options={
                'ordering': ('schoolclass__name', 'date'),
            },
        ),
    ]
